import type { DashboardSummary, Transaction } from "../types";

const SIDEBAR_MENU: { title: string; route: string | undefined }[] = [
  { title: "Dashboard", route: "/" },
  { title: "Transactions", route: undefined },
  { title: "Reports", route: undefined },
  { title: "Settings", route: undefined },
];

const USERS: string[] = [
  "/icons/user-1.svg",
  "/icons/user-2.svg",
  "/icons/user-3.svg",
  "/icons/user-4.svg",
];

const DASHBOARD_SUMMARY: DashboardSummary = {
  totalBalance: 125000.75,
  totalCredits: 98000.5,
  totalDebits: 53000.25,
  transactionCount: 145,
  balanceChange: 4.2,
  creditsChange: 5.6,
  debitsChange: -2.3,
  transactionChange: 1.8,
};
const TRANSACTIONS: Transaction[] = [
  {
    id: "1",
    date: "2025-08-01",
    remark: "Salary",
    amount: 3500,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "2",
    date: "2025-08-02",
    remark: "Groceries",
    amount: -120.45,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "3",
    date: "2025-08-02",
    remark: "Dinner",
    amount: -58.0,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "4",
    date: "2025-08-03",
    remark: "Freelance Payment",
    amount: 780,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "5",
    date: "2025-08-03",
    remark: "Netflix Subscription",
    amount: -15.99,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "6",
    date: "2025-08-04",
    remark: "Electricity Bill",
    amount: -95.5,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "7",
    date: "2025-08-04",
    remark: "Internet Bill",
    amount: -60,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "8",
    date: "2025-08-05",
    remark: "Coffee",
    amount: -4.75,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "9",
    date: "2025-08-06",
    remark: "Gym Membership",
    amount: -45,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "10",
    date: "2025-08-07",
    remark: "Stock Dividends",
    amount: 150,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "11",
    date: "2025-08-07",
    remark: "Lunch",
    amount: -20.25,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "12",
    date: "2025-08-08",
    remark: "Movie Tickets",
    amount: -30,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "13",
    date: "2025-08-08",
    remark: "Project Bonus",
    amount: 300,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "14",
    date: "2025-08-09",
    remark: "Uber Ride",
    amount: -18.75,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "15",
    date: "2025-08-10",
    remark: "Gift Received",
    amount: 200,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "16",
    date: "2025-08-10",
    remark: "Snacks",
    amount: -6.5,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "17",
    date: "2025-08-11",
    remark: "Mobile Recharge",
    amount: -25,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "18",
    date: "2025-08-11",
    remark: "Music Subscription",
    amount: -9.99,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "19",
    date: "2025-08-12",
    remark: "Investment Return",
    amount: 550,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "20",
    date: "2025-08-12",
    remark: "Groceries",
    amount: -110.3,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "21",
    date: "2025-08-13",
    remark: "Doctor Visit",
    amount: -85,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "22",
    date: "2025-08-14",
    remark: "Salary",
    amount: 3500,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "23",
    date: "2025-08-15",
    remark: "House Rent",
    amount: -950,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "24",
    date: "2025-08-16",
    remark: "Dinner",
    amount: -42,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "25",
    date: "2025-08-17",
    remark: "Course Refund",
    amount: 120,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "26",
    date: "2025-08-18",
    remark: "Snacks",
    amount: -5.25,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "27",
    date: "2025-08-19",
    remark: "Stock Sale",
    amount: 950,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "28",
    date: "2025-08-20",
    remark: "Gadget Purchase",
    amount: -320.4,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "29",
    date: "2025-08-20",
    remark: "Freelance Payment",
    amount: 430,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "30",
    date: "2025-08-21",
    remark: "Lunch",
    amount: -22.5,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "31",
    date: "2025-08-22",
    remark: "Book Purchase",
    amount: -40,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "32",
    date: "2025-08-23",
    remark: "Cashback",
    amount: 10,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "33",
    date: "2025-08-24",
    remark: "Coffee",
    amount: -3.5,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "34",
    date: "2025-08-25",
    remark: "Online Course",
    amount: -60,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "35",
    date: "2025-08-26",
    remark: "Internet Bill",
    amount: -65,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "36",
    date: "2025-08-27",
    remark: "Dividends",
    amount: 90,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "37",
    date: "2025-08-28",
    remark: "Transport",
    amount: -12.75,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "38",
    date: "2025-08-29",
    remark: "Concert Ticket",
    amount: -50,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "39",
    date: "2025-08-30",
    remark: "Gift Sent",
    amount: -100,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "40",
    date: "2025-08-31",
    remark: "Project Payment",
    amount: 600,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "41",
    date: "2025-09-01",
    remark: "Coffee",
    amount: -4.25,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "42",
    date: "2025-09-02",
    remark: "Freelance Gig",
    amount: 150,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "43",
    date: "2025-09-03",
    remark: "Lunch",
    amount: -18.25,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "44",
    date: "2025-09-04",
    remark: "Insurance Premium",
    amount: -120,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "45",
    date: "2025-09-05",
    remark: "Stock Profit",
    amount: 500,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "46",
    date: "2025-09-06",
    remark: "Medicine",
    amount: -34.75,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "47",
    date: "2025-09-07",
    remark: "Streaming Service",
    amount: -12.99,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "48",
    date: "2025-09-08",
    remark: "Tutoring",
    amount: 180,
    currency: "USD",
    type: "Credit",
  },
  {
    id: "49",
    date: "2025-09-09",
    remark: "Taxi",
    amount: -25.5,
    currency: "USD",
    type: "Debit",
  },
  {
    id: "50",
    date: "2025-09-10",
    remark: "Bonus",
    amount: 250,
    currency: "USD",
    type: "Credit",
  },
];

export const constants = {
  SIDEBAR_MENU,
  USERS,
  DASHBOARD_SUMMARY,
  TRANSACTIONS,
};
